# Site
repository: etiennemartin/etiennemartin.github.io
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Etienne Martin
title: Staff Software Engineer
email: etienne.m@gmail.com
website: etiennemartin.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
twitter_username: etienne_martin
github_username: etiennemartin
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: etiennemartin
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile_etienne.png
about_content: | # this will include new lines to allow paragraphs
  Hello there! I'm an experienced staff software developer based in Ottawa, Canada, seeking opportunities to contribute to
  impactful projects within a forward-thinking company.

  Recently at Shopify where I was hired as a senior mobile developer, I spend most of time working on their Point of Sale
  application where I grew into the role of Staff Mobile Developer. After 5+ years on the team I chose to pivot to a new
  role within the company. In this new role, I've spent 2+ years where I was tasked with building and maintaining tools
  to load test the Shopify platform.

  Before my time at Shopify, I contributed to the success of Avigilon, regarded as a startup when I joined.
  During this period, I played a pivotal role in the development of their comprehensive Control Center software, covering
  server-side, client-side, and mobile applications.

  Throughout my experiences, I have consistently embraced opportunities to expand my knowledge and skill set. Thriving
  in environments that foster continuous learning and growth, I am now seeking a company that shares this commitment to
  innovation. If you represent such a company, I would be thrilled if you reached out to have a conversation about how
  my skill set and experiences can contribute to your organization.

  For a more detailed overview of my work experience, I invite you to explore my
  [LinkedIn profile](https://www.linkedin.com/in/etiennemartin/). Additionally, you can find some of the small projects
  I've pursued in my spare time on my [GitHub profile](https://github.com/etiennemartin).

content:
  # =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: POM
        link: github.com/etiennemartin/pom
        # link_text: Project Website
        additional_links:
          - title: POM
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          A proof of concept used to show how UI Automation tests can be written. The two guiding
          principles were readability and ease to write. This approach was adopted by the Native Point of Sale app
          at Shopify.
      - layout: top-middle
        title: goja_nodejs
        link: github.com/etiennemartin/goja_nodejs
        # link_text: Project Website
        additional_links:
          - title: goja_nodejs
            icon: fab fa-github
            url: github.com/etiennemartin/goja_nodejs
        description: |
          Contribution to the open source golang module that enables the <mark>NodeJS</mark> [URL API](https://nodejs.org/api/url.html)
          for the [goja runtime](https://github.com/dop251/goja).
      - layout: top-middle
        title: stale-branch-action
        link: github.com/etiennemartin/stale-branch-action
        # link_text: Project Website
        additional_links:
          - title: stale-branch-action
            icon: fab fa-github
            url: github.com/etiennemartin/jugglez
        description: |
          A Github action designed to keep stale branches at bay. The original idea was to reduce abandoned
          branches in repositories where many developers work independently.

  - title: Legacy Projects
    layout: list
    content:
      - layout: top-middle
        title: Jugglez
        link: github.com/etiennemartin/stale-branch-action
        # link_text: Project Website
        additional_links:
          - title: Jugglez
            icon: fab fa-github
            url: github.com/etiennemartin/jugglez
        description: | # this will include new lines to allow paragraphs
          A tiny open-source game that I wrote in a short period of time to learn about <mark>Swift</mark> and <mark>SpriteKit</mark>.
          The original challenge was to complete a working game in a single weekend. After completing that
          challenge I decided to polish it up before open sourcing it.
      - layout: top-middle
        title: GIF-omatic-3D
        link: github.com/etiennemartin/GIF-omatic-3D
        # link_text: Project Website
        additional_links:
          - title: GIF-omatic-3D
            icon: fab fa-github
            url: github.com/etiennemartin/GIF-omatic-3D
        description: | # this will include new lines to allow paragraphs
          A small project used to demo and teach the 3D touch capabilities that had been released by Apple at the time.

  # =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Shopify
        link: shopify.com
        # link_text: boringcompany.com
        sub_title: Staff Software Engineer
        caption: APR 2021 - MAY 2023
        # quote:
        # description: | # this will include new lines to allow paragraphs
        # TBD

      - layout: left
        title: Shopify
        link: shopify.com/pos
        # link_text: boringcompany.com
        sub_title: Staff Mobile Developer
        caption: FEB 2020 - APR 2021
        # quote:
        # description: | # this will include new lines to allow paragraphs
        # TBD

      - layout: left
        title: Avigilon
        link: avigilon.com
        # link_text: boringcompany.com
        sub_title: Staff Software Engineer
        caption: November 2017 - Present
        # quote: >
        #   Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        # description: | # this will include new lines to allow paragraphs
        #   Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  # =-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Mountain biking
      - Tinkering

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
